In [ ]:
import pandas as pd

In [ ]:
# Read data stored in 'balance.txt' into a DataFrame.
df = pd.read_csv('balance.txt', sep=' ')

Notice how we can use the `mean()` function to find average values.

In [ ]:
print("The average income of a female is", df[df.Gender == "Female"].loc[:,"Income"].mean())
print("The average income of a male is",df[df.Gender == "Male"].loc[:,"Income"].mean())

The average income of a female is 44.85392753623188
The average income of a male is 45.610316062176175

Notice how we use the `groupby()` function below.
Find out more about the [groupby function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby) in the pandas documentation.

In [ ]:
df.groupby(['Gender']).mean(numeric_only=True)

,Balance,Income,Limit,Rating,Cards,Age,Education
Gender,,,,,,,
Female,13.41401,44.853928,4756.516908,356.265700,2.927536,55.734300,13.434783
Male,13.44544,45.610316,4713.165803,353.518135,2.989637,55.595855,13.466321

In [ ]:
print("The average age of people in our dataset is", df.loc[:, "Age"].mean())

The average age of people in our dataset is 55.6675

Besides finding average (mean) values we can also find other descriptive statistics such as max and min values. Find more [descriptive statistic methods](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats) in the pandas documentation.

In [ ]:
print("The youngest person in our dataset is", df.loc[:, "Age"].min())
print("The oldest person in our dataset is", df.loc[:, "Age"].max())

The youngest person in our dataset is 23
The oldest person in our dataset is 98